### ISSUE TITLE
OpenAPI implementation could be more memory efficient

### ISSUE THREAD

**Issue by KB-Yomiji** [Yomiji/gkBoot#8]
The OpenAPI saves a copy of an instantiated object. This is unnecessary for interpreting the assignability when the objects are used. Saving the reflective type instead will be more efficient.

**Comment by Yomiji** [comment]
Reviewing this, the changes needed would reduce quality of converting the values to openAPI schema. For example, aliased types do not reconstitute correctly because it is unknown how they are stored or sent to the API schema, so some liberties will need to be made. Closing this issue unless some other solutions come up that are better.
